### ISSUE TITLE
Fatal error with action scheduler in class-wc-payments-fraud-service.php

### ISSUE THREAD

**Issue by fylgjur** [Automattic/woocommerce-payments#1420]
Two users with WooCommerce Subscriptions report fatal errors in WooCommerce Payments breaking the action scheduler and preventing subscription renewal orders from being generated. 

3841610-zen is one of the users. Reported first in p1616344655072200-slack-C7U3Y3VMY 

Stack trace:

```
03-17-2021 @ 15:27:33 - scheduled action 5903 (subscription payment) failed to finish processing due to the following error: Uncaught Error: Call to a member function get_customer_id() on null in /home4/notkyleh/public_html/mitch/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-fraud-service.php:113
Stack trace:
#0 /home4/notkyleh/public_html/mitch/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-fraud-service.php(70): WC_Payments_Fraud_Service->prepare_sift_config(Array)
#1 /home4/notkyleh/public_html/mitch/wp-includes/class-wp-hook.php(292): WC_Payments_Fraud_Service->prepare_fraud_config(Array, 'sift')
#2 /home4/notkyleh/public_html/mitch/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array)
#3 /home4/notkyleh/public_html/mitch/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php(204): apply_filters('wcpay_prepare_f...', Array, 'sift')
#4 /home4/notkyleh/public_html/mitch/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php(1744): WC_Payments_Account->get_fraud_services_config()
#5 /home4/notkyleh/public_html/mitch/wp-content
03-17-2021 @ 15:27:33 - action args: subscription_id: 1014
```

**Comment by shohanhossainnab** [comment]
Similar case here: 3842767-zen

**Comment by AashikP** [comment]
Another report in 3845196-zen

**Comment by vbelolapotkov** [comment]
Fixed by #1424 and [released with v2.1.1](https://wordpress.org/plugins/woocommerce-payments).

**Comment by fylgjur** [comment]
Thank you for the fast work! I have let all the users who reported this know about the update.

**Comment by mouligreenlaw** [comment]
This ticket appears to be an occurrence of this issue after the update as they are using WC Pay 2.2.0
3877142-zen
