### ISSUE TITLE
Customer Multi-Currency fatal if store currency is changed

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2068]
If you go to WooCommerce > Settings > Multi-Currency, and then enable currencies, such as CAD and BIF, then go to Settings > General and change the currency to Euro, it will create a fatal error. This may be due to the enabled currencies array in the database doesn't have the new default currency in it. 

In my test I had USD as my store currency, enabled CAD and BIF, then switch to Euro as my store currency and one error stated USD was not an index. I believe this is due to the mock available currencies does not have USD in it, this then causes a downward spiral.

> Notice: Undefined index: USD in /Users/j/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/multi-currency/class-multi-currency.php on line 267

> Fatal error: Uncaught Error: __clone method called on non-object in /Users/j/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/multi-currency/class-multi-currency.php:267 Stack trace: #0 /Users/j/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/multi-currency/class-multi-currency.php(98): WCPay\Multi_Currency\Multi_Currency->initialize_enabled_currencies() #1 /Users/j/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/multi-currency/class-multi-currency.php(89): WCPay\Multi_Currency\Multi_Currency->init() #2 /Users/j/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/multi-currency/class-multi-currency.php(79): WCPay\Multi_Currency\Multi_Currency->__construct() #3 /Users/j/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/multi-currency/wc-payments-multi-currency.php(21): WCPay\Multi_Currency\Multi_Currency::instance() #4 /Users/j/sites/wcpay/wp-includes/class-wp-hook.php(292): WC_Payments_Multi_Currency('') #5 /Users/j/sites/wcpay/wp-includes/class-wp-hook.php(316): W in /Users/j/sites/wcpay/wp-content/plugins/woocommerce-payments/includes/multi-currency/class-multi-currency.php on line 267

**Comment by jessepearson** [comment]
Closed via #2078
