### ISSUE TITLE
Critical error related with WC-Analytics + MC on user blog

### ISSUE THREAD

**Issue by tpaksu** [Automattic/woocommerce-payments#2686]
User on 4204764-zd-woothemes claims to see this on the new 2.8.2 release:

```
2021-08-07T02:07:07+00:00 CRITICAL Uncaught TypeError: Return value of WCPayMultiCurrencyMultiCurrency::get_default_currency() must be an instance of WCPayMultiCurrencyCurrency, null returned in /home2/mmtwomar/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php:511
Stack trace:
#0 /home2/mmtwomar/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/Analytics.php(232): WCPayMultiCurrencyMultiCurrency->get_default_currency()
#1 /home2/mmtwomar/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/Analytics.php(108): WCPayMultiCurrencyAnalytics->should_convert_order_stats(Object(AutomatticWooCommerceAdminOverridesOrder))
#2 /home2/mmtwomar/public_html/wp-includes/class-wp-hook.php(303): WCPayMultiCurrencyAnalytics->update_order_stats_data(Array, Object(AutomatticWooCommerceAdminOverridesOrder))
#3 /home2/mmtwomar/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array)
#4 /home2/mmtwomar/public_html/wp-content/plugins/woo in /home2/mmtwomar/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php on line 511
```

What may have cause this? If there are no available currencies, even the default one on the array, it may give this, but I think it's still a hook running before the MC is initialized.

**Comment by tpaksu** [comment]
One possibility, `update_order_stats` method tries to run on sites that the users haven't finished the MC onboarding and seeing the CTA.

**Comment by tpaksu** [comment]
This is caused by MC Analytics hook trying to update order data when MC isn't initialized because of incomplete onboarding. Possible solutions:

1. Also prevent loading of MC Analytics when onboarding isn't complete
2. Add check before using MC related method which will throw an error when uninitialized
3. Initialize MC with minimum data 

The third will solve other issues that's related with uninitialized MC too.

**Comment by thuautp** [comment]
Also reported in 4214076-zen

**Comment by tpaksu** [comment]
@thuautp it's being/been fixed in #2696.

**Comment by jessepearson** [comment]
The fix for this was release yesterday.
