### ISSUE TITLE
Critical error with WooCommerce Subscriptions

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#2687]
This looks likely related to #2686 but the message and stack are both a bit different and the user says it only happens with a subscription product:

```
[09-Aug-2021 01:42:39 UTC] PHP Fatal error:  Uncaught TypeError: Return value of WCPay\MultiCurrency\MultiCurrency::get_enabled_currencies() must be of the type array, null returned in /home/sitename/public_html/tutor/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php:520
Stack trace:
#0 /home/sitename/public_html/tutor/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php(554): WCPay\MultiCurrency\MultiCurrency->get_enabled_currencies()
#1 /home/sitename/public_html/tutor/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php(650): WCPay\MultiCurrency\MultiCurrency->get_selected_currency()
#2 /home/sitename/public_html/tutor/wp-content/plugins/woocommerce-payments/includes/multi-currency/Compatibility.php(75): WCPay\MultiCurrency\MultiCurrency->get_price('90', 'product')
#3 /home/sitename/public_html/tutor/wp-includes/class-wp-hook.php(303): WCPay\MultiCurrency\Compatibility->get_subscription_product_price('90', Object(WC_Product_Subscription))
#4 /home in /home/sitename/public_html/tutor/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php on line 520
```

4207816-zen

**Comment by jessepearson** [comment]
The [`initialize_enabled_currencies` method](https://github.com/Automattic/woocommerce-payments/blob/2.8.2/includes/multi-currency/MultiCurrency.php#L446-L485) has an error in it. It assumes that `$enabled_currency_codes` is at least going to have the default currency in it, but it's empty.

**Comment by thuautp** [comment]
Also reported in 4213960-zen, 4203353-zen

**Comment by sukafia** [comment]
Another report 4220317-zen

**Comment by nixiack** [comment]
Issue seems the same in 4226659-Zen.

Same error:
`Fatal error: Uncaught TypeError: Return value of WCPayMultiCurrencyMultiCurrency::get_enabled_currencies() must be of the type array, null returned in /home/customer/www/cheersmt.com/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php:520 Stack trace: #0 /home/customer/www/cheersmt.com/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php(554): WCPayMultiCurrencyMultiCurrency->get_enabled_currencies() #1 /home/customer/www/cheersmt.com/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php(650): WCPayMultiCurrencyMultiCurrency->get_selected_currency() #2 /home/customer/www/cheersmt.com/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/Compatibility.php(75): WCPayMultiCurrencyMultiCurrency->get_price('119.88', 'product') #3 /home/customer/www/cheersmt.com/public_html/wp-includes/class-wp-hook.php(303): WCPayMultiCurrencyCompatibility->get_subscription_product_price('11 in /home/customer/www/cheersmt.com/public_html/wp-content/plugins/woocommerce-payments/includes/multi-currency/MultiCurrency.php on line 520`

Testing with our SS test account I cannot readily replicate, but it seems isolated to just WC Pay, it shows on Checkout.  They do not have a multi-currency plugin installed per the SSR.

**Comment by sukafia** [comment]
Another one 4226467-zen

**Comment by jessepearson** [comment]
The fix for this was released yesterday, sorry for not noting that here at that time.
