### ISSUE TITLE
Partial refund via WC Payments show no error, but is not reflected in Stripe (or in the order notes)

### ISSUE THREAD

**Issue by diegocurbelo** [Automattic/woocommerce-payments#2866]
### Describe the bug
Processing a partial refund via WooCommerce Payments shows as successful, but it doesn't appear to have worked.

The products show as returned and there is a line item for the refund, but there is no info in the logs, order notes, or the merchant's Stripe dashboard.

The merchant tried deleting the line item and re-attempting the refund but the same issue seems to have occurred. They mentioned that it seemed to hang during the process and inspected the browser console, which showed the following request failed:
`<host>/wp-admin-admin-ajax.php` returns status code: `500`

And the logs show this error:
```
2021-09-07T14:38:09+00:00 CRITICAL Uncaught TypeError: Argument 1 passed to WCS_Related_Order_Store_CPT::get_related_subscription_ids() must be an instance of WC_Order, instance of Automattic\WooCommerce\Admin\Overrides\OrderRefund given, called in <redacted>/public_html/wp-content/plugins/woocommerce-subscriptions/includes/wcs-order-functions.php on line 73 and defined in <redacted>/public_html/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-related-order-store-cpt.php:92
Stack trace:
#0 <redacted>/public_html/wp-content/plugins/woocommerce-subscriptions/includes/wcs-order-functions.php(73): WCS_Related_Order_Store_CPT->get_related_subscription_ids()
#1 <redacted>/public_html/wp-content/plugins/woocommerce-subscriptions/includes/wcs-renewal-functions.php(117): wcs_get_subscriptions_for_order()
#2 <redacted>/public_html/wp-content/plugins/woocommerce-subscriptions in <redacted>/public_html/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-related-order-store-cpt.php on line 92
```

Originally reported in this ticket: 4271280-zd-woothemes

### Actual behavior
The partial refund completes in the UI, but no order note is added to the order, and no refund is created in Stripe.

### Expected behavior
The partial refund completes successfully, an order note is added to the order and the refund transaction is created in Stripe.

### Additional context
- 4271280-zd-woothemes

**Comment by diegocurbelo** [comment]
Seems to be an error in WooCommerce Subscriptions: 4186-gh-woocommerce/woocommerce-subscriptions, last comment from that issue:
> Btw, this was causing Stripe refunds on non-subscription related orders to not pass the refund information over to Stripe, so they had to do it manually for now.

**Comment by ForestParks** [comment]
I'm seeing this same error. Has there been any updates or progress made yet? All refunds have to be run manually.

**Comment by thenbrent** [comment]
@ForestParks we have an open patch for a suspected bug now (internal reference: 4188-gh-woocommerce/woocommerce-subscriptions); however, we have been unable to reproduce this issue so have also been unable to confirm if that patch will fix the issue.

If you have not already, please submit a ticket with as much information about the error on your site (steps to reproduce, error logs, logins if possible etc.) via https://woocommerce.com/my-account/create-a-ticket/?select=5278104

We can then work with you to resolve it there.

**Comment by aheckler** [comment]
@ForestParks Also, one thing to clarify: with WooCommerce Payments, merchants will not be able to access the Stripe dashboard. So if you are refunding manually in WooCommerce, please be aware that doing so *will not* actually send the customer back their money! It only alters the WooCommerce order to appear as refunded; no money actually changes hand unless you email us and tell us (meaning, WooCommerce.com support staff) to issue a refund from within Stripe ourselves.

**Comment by haszari** [comment]
As noted by @thenbrent [above](https://github.com/Automattic/woocommerce-payments/issues/2866#issuecomment-917816776), the next step here is to confirm steps to reproduce the issue.
