### ISSUE TITLE
Orphaned WC Pay Subscriptions cause fatal error in Stripe transaction log

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#4424]
### Describe the bug

In 5347746-zen multiple duplicate WC Payments Subscriptions were created on checkout on two separate occasions. This left two live subscriptions on the site, one for each customer, along with seven live WC Pay Subscriptions. As each subscription billed, the subscriptions that did not exist on the site caused a fatal error.

### Actual behavior

Customer A

`sub_1L5AgH2ELJ4k4DvBJ9Vuxgvm` -> on site
`sub_1L5AfJ2ELJ4k4DvBPRWtOQqb` -> no record on site
`sub_1L5Aa52ELJ4k4DvBARQfHqzE` -> no record on site

Customer B

`sub_1L3nA82ELJ4k4DvB5howWCGK` -> on site
`sub_1L3n8x2ELJ4k4DvBYiIRxBGE` -> no record on site
`sub_1L3n852ELJ4k4DvBDyTWHsk6` -> no record on site
`sub_1L3n5d2ELJ4k4DvBG7mlc2iD` ->  no record on site

When the non-existent subscriptions billed, a fatal error occurred and was recorded in the Stripe transaction log.

```
2022-07-01T04:28:01+00:00 ERROR WCPay\Exceptions\Invalid_Webhook_Data_Exception: Cannot find subscription for the incoming "invoice.paid" event. in /home/customer/www/alsdrumschool.co.uk/public_html/wp-content/plugins/woocommerce-payments/includes/subscriptions/class-wc-payments-subscriptions-event-handler.php:100
Stack trace:
#0 /home/customer/www/alsdrumschool.co.uk/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-webhook-processing-service.php(170): WC_Payments_Subscriptions_Event_Handler->handle_invoice_paid(Array)
#1 /home/customer/www/alsdrumschool.co.uk/public_html/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-rest-payments-webhook-controller.php(80): WC_Payments_Webhook_Processing_Service->process(Array)
#2 /home/customer/www/alsdrumschool.co.uk/public_html/wp-includes/rest-api/class-wp-rest-server.php(1143): WC_REST_Payments_Webhook_Controller->handle_webhook(Object(WP_REST_Request))
```

### Screenshots

All data in 5347746-zen, including logs.

### Expected behavior

A subscription that exists in WC Payments Stripe dashboard but does not exist on the site should be handled.

**Comment by haszari** [comment]
If there's a way we can reproduce the fatal error (sounds readily possible!) then we should fix the hook handler so it's robust to that situation.

There may also be an opportunity to warn/inform the merchant about the MIA / broken subscriptions – i.e. make the log more useful, or surface the error in the UI.

**Comment by nicdwilson** [comment]
I believe a good approach would be to listen for `invoice.finalized `

This event takes place _before_ the subscription renewal runs. If the handler listened for this event, and it was received for a subscription that does not exist, we would then be able to void the invoice and cancel the orphaned subscription before the customer is billed.

A customer billed by an orphaned subscription receives no notification, and the merchant sees only an amount without any idea what is being paid for or by whom. The merchant has no access to be able to cancel the orphaned subscription.

Logging an notifications which take place at `invoice.finalized ` are therefore more proactive, and prevent duplicate billing and related complications.

**Comment by haszari** [comment]
Deprioritising this as we have not had many reports of it, and no way to reproduce yet. Please comment/ping if we find a way to reproduce this or if it should be prioritised.

**Comment by frosso** [comment]
Closing — this is specific to orphaned Stripe Billing subscriptions sending `invoice.paid` webhooks with no matching WooCommerce record. WCPay Subscriptions (Stripe Billing) was deprecated in Feb 2025 — subscriptions are no longer created or billed via Stripe's billing engine.
