### ISSUE TITLE
TypeError when updating customer without user object

### ISSUE THREAD

**Issue by KarlisJ** [Automattic/woocommerce-payments#4639]
### Describe the bug
Error logs contain 

```
2022-08-25T00:28:46+00:00 CRITICAL Uncaught TypeError: Argument 2 passed to WC_Payments_Customer_Service::update_customer_for_user() must be an instance of WP_User, bool given, called in /home2/smartwatchforles/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php on line 1054 and defined in /home2/smartwatchforles/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-customer-service.php:158
Stack trace:
#0 /home2/smartwatchforles/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php(1054): WC_Payments_Customer_Service->update_customer_for_user('cus_MJ67TPzYO5r...', false, Array)
#1 /home2/smartwatchforles/public_html/wp-includes/class-wp-hook.php(307): WC_Payment_Gateway_WCPay->update_customer_with_order_data(4543, 'cus_MJ67TPzYO5r...')
#2 /home2/smartwatchforles/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#3 /home2/smartwatchforles/public_html/wp-includes/plugin.php(524): WP_Hook->do_action(Array in /home2/smartwatchforles/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-customer-service.php on line 158
```

### To Reproduce
Need to be derived from the stack trace. The merchant who notified us about this did not have their payment failing, so this behavior is happening asynchronously.

### Additional context
5505814-zd-woothemes

`$user  = $order->get_user()` can return `false` but `update_customer_for_user` has typehint for `WC_User`

**Comment by KarlisJ** [comment]
Another ticket 5501948-zd-woothemes has the same error in logs (though not causing any issues)
