### ISSUE TITLE
Fatal Error accessing SearchWP admin page when WooCommerce Payments in active with PHP 8

### ISSUE THREAD

**Issue by Luminus** [Automattic/woocommerce-payments#5270]
### Describe the bug

When trying to access the admin page for WPSearch while running PHP 8.0, a Fatal Error is thrown. Works fine in older PHP versions.

Stack Trace from `debug.log`:

```
Warning: Trying to access array offset on value of type bool in /home/vagrant/code/merrittproducts/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php on line 439

Warning: Trying to access array offset on value of type bool in /home/vagrant/code/merrittproducts/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php on line 547

Warning: Trying to access array offset on value of type bool in /home/vagrant/code/merrittproducts/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php on line 563

Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /home/vagrant/code/merrittproducts/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php:563 Stack trace: #0 /home/vagrant/code/merrittproducts/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php(563): array_merge() #1 /home/vagrant/code/merrittproducts/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php(637): WC_Payments_Admin->register_payments_scripts() #2 /home/vagrant/code/merrittproducts/wp-includes/class-wp-hook.php(308): WC_Payments_Admin->enqueue_payments_scripts() #3 /home/vagrant/code/merrittproducts/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #4 /home/vagrant/code/merrittproducts/wp-includes/plugin.php(517): WP_Hook->do_action() #5 /home/vagrant/code/merrittproducts/wp-content/plugins/searchwp/includes/Admin/OptionsView.php(190): do_action() #6 /home/vagrant/code/merrittproducts/wp-includes/class-wp-hook.php(308): SearchWP\Admin\OptionsView::legacy_assets() #7 /home/vagrant/code/merrittproducts/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #8 /home/vagrant/code/merrittproducts/wp-includes/plugin.php(517): WP_Hook->do_action() #9 /home/vagrant/code/merrittproducts/wp-admin/admin-header.php(118): do_action() #10 /home/vagrant/code/merrittproducts/wp-admin/admin.php(239): require_once('...') #11 {main} thrown in /home/vagrant/code/merrittproducts/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-payments-admin.php on line 563
```

### To Reproduce

1. Install SearchWP
2. Go to the settings page - `/wp-admin/admin.php?page=searchwp-settings`
3. See the error, but only with PHP 8.0

### Actual behavior

A Fatal Error is thrown.

### Expected behavior

The SearchWP settings page should be accessible, and WooCommerce Payments should not be throwing a Fatal Error.

### Additional context

25865891-hc

**Comment by zmaglica** [comment]
@Luminus I wasn't able to reproduce an error with multiple PHP versions (7.4, 8.0 and 8.1). In normal circumstances, you won't have this error (when you download ZIP file of plugin that is already built). If you load a plugin into development environment, you would need to build assets and maybe that's the reason why it is failing.

**Comment by naman03malhotra** [comment]
Please re-open the issue if you can replicate it.
