### ISSUE TITLE
PHP Fatal errors - Ver 5.6.0 on Atomic - Uncaught TypeError: WC_Payments_Order_Success_Page::add_notice_previous_paid_order

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#5816]
### Describe the bug

Internal link - 2f857-pb

Error: 
```
PHP Fatal error:  Uncaught TypeError: WC_Payments_Order_Success_Page::add_notice_previous_paid_order(): Argument #1 ($text) must be of type string, null given, called in /wordpress/core/6.1.1/wp-includes/class-wp-hook.php on line 310 and defined in /wordpress/plugins/woocommerce-payments/5.6.0/includes/class-wc-payments-order-success-page.php:80
Stack trace:
#0 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(310): WC_Payments_Order_Success_Page->add_notice_previous_paid_order(NULL)
#1 /wordpress/core/6.1.1/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/plugins/woocommerce/7.5.0/templates/checkout/thankyou.php(42): apply_filters('woocommerce_tha...', 'Gracias. Tu ped...', Object(Automattic\WooCommerce\Admin\Overrides\Order))
#3 /wordpress/plugins/woocommerce/7.5.0/includes/wc-core-functions.php(345): include('/wordpress/plug...')
#4 /wordpress/plugins/woocommerce/7.5.0/includes/shortcodes/class-wc-shortcode-checkout.php(279): wc_get_template('checkout/thanky...', Array)
#5 /wordpress/plugins/woocommerce/7.5.0/includes/shortcodes/class-wc-shortcode-checkout.php(63): WC_Shortcode_Checkout::order_received(1054)
#6 /wordpress/plugins/woocommerce/7.5.0/includes/class-wc-shortcodes.php(72): WC_Shortcode_Checkout::output('')
#7 /wordpress/plugins/woocommerce/7.5.0/includes/class-wc-shortcodes.php(95): WC_Shortcodes::shortcode_wrapper(Array, '')
#8 /wordpress/core/6.1.1/wp-includes/shortcodes.php(355): WC_Shortcodes::checkout('', '', 'woocommerce_che...')
#9 [internal function]: do_shortcode_tag(Array)
#10 /wordpress/core/6.1.1/wp-includes/shortcodes.php(227): preg_replace_callback('/\\[(\\[?)(woocom...', 'do_shortcode_ta...', '[woocommerce_ch...')
#11 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): do_shortcode('[woocommerce_ch...')
#12 /wordpress/core/6.1.1/wp-includes/plugin.php(205): WP_Hook->apply_filters('[woocommerce_ch...', Array)
#13 /wordpress/plugins/gutenberg/15.3.1/build/block-library/blocks/post-content.php(54): apply_filters('the_content', '<!-- wp:shortco...')
#14 /wordpress/core/6.1.1/wp-includes/class-wp-block.php(256): gutenberg_render_block_core_post_content(Array, '<!-- wp:shortco...', Object(WP_Block))
#15 /wordpress/core/6.1.1/wp-includes/class-wp-block.php(242): WP_Block->render()
#16 /wordpress/core/6.1.1/wp-includes/blocks.php(1051): WP_Block->render()
#17 /wordpress/core/6.1.1/wp-includes/blocks.php(1089): render_block(Array)
#18 /wordpress/core/6.1.1/wp-includes/block-template.php(240): do_blocks('<!-- wp:templat...')
#19 /wordpress/core/6.1.1/wp-includes/template-canvas.php(12): get_the_block_template_html()
#20 /wordpress/core/6.1.1/wp-includes/template-loader.php(106): include('/wordpress/core...')
#21 /wordpress/core/6.1.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#22 /wordpress/core/6.1.1/index.php(17): require('/wordpress/core...')
#23 {main}
  thrown in /wordpress/plugins/woocommerce-payments/5.6.0/includes/class-wc-payments-order-success-page.php on line 80
``` 
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

cc @shendy-a8c @cesarcosta99 as release leads, and @Automattic/gamma  for having a look.

**Comment by htdat** [comment]
I am looking into this one.

**Comment by shendy-a8c** [comment]
@htdat, I believe this issue should have been closed when https://github.com/Automattic/woocommerce-payments/pull/5818 was merged, right?

**Comment by htdat** [comment]
That's right. Thanks @shendy-a8c. I am closing this now.
