### ISSUE TITLE
Payment request button -  Two different fatal error logs

### ISSUE THREAD

**Issue by jbordonado** [Automattic/woocommerce-payments#5906]
### Describe the bug

For some time, I've seen two errors stemming from the file `includes/class-wc-payments-payment-request-button-handler.php` on Atomic sites. It's not new, but we should take the time to fix them.

Grafana dashboard: [link](https://mc.a8c.com/grafana/d/o7i4CqH4z/wc-pay-additional?orgId=1&var-hvm_blogID=All&var-tag_value=&var-log_level=error&var-e2e_blogID=211482617&var-webhook_url=All&var-last_wcpay_version=5.6.2&var-atomic_logs_severity=Fatal%20error&var-Filters=file%7C%3D%7C%2Fwordpress%2Fplugins%2Fwoocommerce-payments%2F5.6.2%2Fincludes%2Fclass-wc-payments-payment-request-button-handler.php)

## First error

```
PHP Fatal error:  Uncaught Error: Call to a member function needs_shipping() on bool in /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php:803
Stack trace:
#0 /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php(530): WC_Payments_Payment_Request_Button_Handler->is_product_supported()
#1 /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php(158): WC_Payments_Payment_Request_Button_Handler->should_show_payment_request_button()
#2 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): WC_Payments_Payment_Request_Button_Handler->set_session('')
#3 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/core/6.2/wp-includes/template-loader.php(13): do_action('template_redire...')
#6 /wordpress/core/6.2/wp-blog-header.php(19): require_once('/wordpress/core...')
#7 /wordpress/core/6.2/index.php(17): require('/wordpress/core...')
#8 {main}
  thrown in /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php on line 803
```

https://github.com/Automattic/woocommerce-payments/blob/e6d1a56ee45dff756b7c0767dbddccf385f27345/includes/class-wc-payments-payment-request-button-handler.php#L789-L834

I think we may just need to use if/elseif to avoid going through all the cases and risk calling a method on a product that is falsy.

## Second error

```
PHP Fatal error:  Uncaught Error: Call to a member function get_type() on bool in /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php:1116
Stack trace:
#0 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): WC_Payments_Payment_Request_Button_Handler->ajax_add_to_cart('')
#1 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wordpress/plugins/woocommerce/7.5.1/includes/class-wc-ajax.php(94): do_action('wc_ajax_wcpay_a...')
#4 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): WC_AJAX::do_wc_ajax('')
#5 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(false, Array)
#6 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/core/6.1.1/wp-includes/template-loader.php(13): do_action('template_redire...')
#8 /wordpress/core/6.1.1/wp-blog-header.php(19): require_once('/wordpress/core...')
#9 /wordpress/core/6.1.1/index.php(17): require('/wordpress/core...')
#10 {main}
  thrown in /wordpress/plugins/woocommerce-payments/5.6.2/includes/class-wc-payments-payment-request-button-handler.php on line 1116
```

https://github.com/Automattic/woocommerce-payments/blob/e6d1a56ee45dff756b7c0767dbddccf385f27345/includes/class-wc-payments-payment-request-button-handler.php#L1101-L1141

For that one, I'm not sure what is going on

### To Reproduce
Unclear

**Comment by RadoslavGeorgiev** [comment]
Tagging @Automattic/fusion as a part of the backlog prioritization, in accordance with Pc2DNy-3z-p2.

**Comment by Vegetahmet** [comment]
Hey Guys, i have also the same Error. Apple Pay is not working on my site . Do you have updates?
