### ISSUE TITLE
Fatal error during subscription renewal, calling __unset() on null

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#6208]
### Describe the bug

Similar to https://github.com/Automattic/woocommerce-payments/issues/3892

Customer has reported the following fatal error when processing a subscription renewal:

```
Error: 05-03-2023 @ 05:06:03 - scheduled action 189117 (subscription payment retry) failed to finish processing due to the following error: Uncaught Error: Call to a member function __unset() on null in /var/www/vhosts /acxqhtjf.host270.checkdomain.de/clavis-schule.de/wp-content/plugins/woocommerce-payments/includes/payment-methods/class-upe-payment-gateway.php:1227 

The lines in the stack trace about the imagify plugin
#28 /var/www/vhosts/acxqhtjf.host270.checkdomain.de/clavis-schule.de/wp-content/plugins/imagify/inc/Dependencies/ActionScheduler/classes/actions/ActionScheduler_Action.php(43): do_action_ref_array( 'woocommerce_sch...', Array)
#29 /var/www/vhosts/acxqhtjf.host270.checkdomain.de/clavis-schule.de/wp-content/plugins/imagify/inc/Dependencies/ActionScheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(65): ActionScheduler_Action- >execute()
#30 /var/www/vhosts/acxqhtjf.host270.checkdomain.de/clavis-schule.de/wp-content/plugins/imagify/inc/Dependencies/ActionScheduler/classes/ActionScheduler_QueueRunner.php(166): ActionScheduler_Abstract_QueueRunner->process_action (189117, 'WP Cron')
#31 /var/www/vhosts/acxqhtjf.host270.checkdomain.de/clavis-schule.de/wp-content/plugins/imagify/inc/Dependencies/ActionScheduler/classes/ActionScheduler_QueueRunner.php(136): ActionScheduler_QueueRunner->do_batch (25, 'WP Cron')
```

Similar to the changes needed to fix the previous issue, we should surround the `WC()->session->__unset( self::KEY_UPE_SETUP_INTENT );` with a check for `WC()->session`:

```
if ( isset( WC()->session ) ) {
	WC()->session->__unset( self::KEY_UPE_SETUP_INTENT );
}
```

### Additional context

 - 6256721-zen
 - p1683118795080759-slack-C7U3Y3VMY

**Comment by kaushikasomaiya** [comment]
Note: This error doesn't seem to be affecting the renewals - it gets logged after the renewal is successful.
