### ISSUE TITLE
Fix flaky UPE tests

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#6322]
### Describe the bug

Frequently yet intermittently, the two tests "WC - latest | upe - shopper" and "WC - latest | UPESplit - shopper" keep failing in GH actions for WCPay PRs. 

There are some problems with the new UPE deferred intent E2E tests, but the UPE E2E tests also appear to have an issue on [this line](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/specs/upe-split/shopper/shopper-upe-enabled-all-flows.spec.js#L23) where SEPA is enabled, more specifically causing an error on [this line](https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/utils/flows.js#L479) where the node/button in question appears not to exist.

### To Reproduce

1. Go to any recent PR and check out the failing tests. 

### Actual behavior

[Example failed jobs](https://github.com/Automattic/woocommerce-payments/actions/runs/5002564246/jobs/8962671002?pr=6028).

UPE tests fail...
```bash
FAIL tests/e2e/specs/upe/shopper/shopper-upe-enabled-all-flows.spec.js (77.377 s)
  Enabled UPE
    Shortcode checkout
      ✕ should save the card (18494 ms)
      ✕ should process a payment with the saved card (10919 ms)
      ✕ should delete the card (3199 ms)
    My Account
      ✕ should add the card as a new payment method (8751 ms)
      ✕ should be able to delete the card (2085 ms)

  ● Enabled UPE › Shortcode checkout › should save the card

    Node is either not visible or not an HTMLElement

      477 | 			);
      478 | 			if ( tourKitDismissButton ) {
    > 479 | 				await tourKitDismissButton.click();
          | 				^
      480 | 			}
      481 |
      482 | 			await page.$eval( paymentMethod, ( method ) => method.click() );

      at ElementHandle._clickablePoint (node_modules/puppeteer/lib/JSHandle.js:221:13)
          at runMicrotasks (<anonymous>)
      at ElementHandle.click (node_modules/puppeteer/lib/JSHandle.js:282:20)
      at Object.enablePaymentMethod (tests/e2e/utils/flows.js:479:5)
      at Object.<anonymous> (tests/e2e/specs/upe/shopper/shopper-upe-enabled-all-flows.spec.js:23:3)
        -- ASYNC --
      at ElementHandle.click (node_modules/puppeteer/lib/helper.js:111:15)
      at Object.enablePaymentMethod (tests/e2e/utils/flows.js:479:32)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (tests/e2e/specs/upe/shopper/shopper-upe-enabled-all-flows.spec.js:23:3)
```

UPE split tests fail...
```bash
  ● Enabled enhanced UPE › should successfully place order with the default card

    Node is either not visible or not an HTMLElement

      474 | 			);
      475 | 			if ( tourKitDismissButton ) {
    > 476 | 				await tourKitDismissButton.click();
          | 				^
      477 | 			}
      478 |
      479 | 			await page.$eval( paymentMethod, ( method ) => method.click() );

      at ElementHandle._clickablePoint (node_modules/puppeteer/lib/JSHandle.js:221:13)
          at runMicrotasks (<anonymous>)
      at ElementHandle.click (node_modules/puppeteer/lib/JSHandle.js:282:20)
      at Object.enablePaymentMethod (tests/e2e/utils/flows.js:476:5)
      at Object.<anonymous> (tests/e2e/specs/upe-split/shopper/shopper-deferred-intent-creation-upe-enabled.spec.js:31:3)
        -- ASYNC --
      at ElementHandle.click (node_modules/puppeteer/lib/helper.js:111:15)
      at Object.enablePaymentMethod (tests/e2e/utils/flows.js:476:32)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (tests/e2e/specs/upe-split/shopper/shopper-deferred-intent-creation-upe-enabled.spec.js:31:3)
```

### Screenshots

See above.

### Expected behavior

Tests should not fail arbitrarily.

### Desktop (please complete the following information):

N/A

### Smartphone (please complete the following information):

N/A

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/6322?planning-poker) with Zenhub @mdmoore @timur27
