### ISSUE TITLE
Fatal Error: Call to undefined method WCS_Staging::is_duplicate_site() 

### ISSUE THREAD

**Issue by ezific** [Automattic/woocommerce-payments#6636]
### Describe the bug
WP critical error page is displayed / wp-admin & front end are non-functional.

### To Reproduce
First noticed this issue after upgrade from version 5.9.1 to 6.0.0) 

Currently occurring in WP 6.2.2
WooCommerce payments v6.1.1
PHP 8.2

### Stack Trace
```
[30-Jun-2023 02:52:19 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WCS_Staging::is_duplicate_site() in /home/site/public_html/wp-content/plugins/woocommerce-payments/includes/subscriptions/class-wc-payments-subscriptions.php:132
Stack trace:
#0 /home/site/public_html/wp-content/plugins/woocommerce-payments/includes/subscriptions/class-wc-payments-product-service.php(91): WC_Payments_Subscriptions::is_duplicate_site()
#1 /home/site/public_html/wp-content/plugins/woocommerce-payments/includes/subscriptions/class-wc-payments-subscriptions.php(76): WC_Payments_Product_Service->__construct()
#2 /home/site/public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php(605): WC_Payments_Subscriptions::init()
#3 /home/site/public_html/wp-content/plugins/woocommerce-payments/woocommerce-payments.php(152): WC_Payments::init()
#4 /home/site/public_html/wp-includes/class-wp-hook.php(308): wcpay_init()
#5 /home/site/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#6 /home/site/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /home/site/public_html/wp-settings.php(486): do_action()
#8 /home/site/public_html/wp-config.php(75): require_once('/home/site/...')
#9 /home/site/public_html/wp-load.php(50): require_once('/home/site/...')
#10 /home/site/public_html/wp-blog-header.php(13): require_once('/home/site/...')
#11 /home/site/public_html/index.php(17): require('/home/site/...')
#12 {main}
  thrown in /home/site/public_html/wp-content/plugins/woocommerce-payments/includes/subscriptions/class-wc-payments-subscriptions.php on line 132
```

### To Fix
I modified /class-wc-payments-subscriptions.php:132 as follows which fixes the problem as a temporary solution

```
public static function is_duplicate_site() {
		return false; //class_exists( 'WCS_Staging' ) && WCS_Staging::is_duplicate_site();
	}
```

**Comment by zmaglica** [comment]
This issue impacts WCPay Subscription, so assigning to Helix (based on team responsibilities) @haszari . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by mattallan** [comment]
Fixed with: https://github.com/Automattic/woocommerce-payments/pull/6489
