### ISSUE TITLE
Onboarding WCPay via Woo Express triggers fatal error related to fraud rulesets

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#6851]
### Describe the bug
When onboarding WooPayments on a fresh Woo Express site, it can produce the following fatal error:

```
2023-07-12T23:55:56+00:00 CRITICAL Uncaught WCPay\Exceptions\API_Exception: Error: Unexpected server error. in /wordpress/plugins/woocommerce-payments/6.1.1/includes/wc-payment-api/class-wc-payments-api-client.php:2009
Stack trace:
#0 /wordpress/plugins/woocommerce-payments/6.1.1/includes/wc-payment-api/class-wc-payments-api-client.php(1835): WC_Payments_API_Client->check_response_for_errors(Array)
#1 /wordpress/plugins/woocommerce-payments/6.1.1/includes/wc-payment-api/class-wc-payments-api-client.php(1641): WC_Payments_API_Client->request(Array, 'fraud_ruleset', 'POST')
#2 /wordpress/plugins/woocommerce-payments/6.1.1/includes/class-wc-payment-gateway-wcpay.php(2381): WC_Payments_API_Client->save_fraud_ruleset(Array)
#3 /wordpress/plugins/woocommerce-payments/6.1.1/includes/class-wc-payment-gateway-wcpay.php(2314): WC_Payment_Gateway_WCPay->maybe_refresh_fraud_protection_settings()
#4 /wordpress/plugins/woocommerce-payments/6.1.1/includes/class-wc-payment-gateway-wcpay.php(1740): WC_Payment_Gateway_WCPay->get_current_protection_level()
#5 /wordpress/plugins/woocommerce-payments/6.1.1/includes/admin/class-wc-rest-payments-settings-controller.php(400): WC_Payment_Gateway_WCPay->get_option('current_protect...')
#6 /wordpress/core/6.2.2/wp-includes/rest-api/class-wp-rest-server.php(1181): WC_REST_Payments_Settings_Controller->get_settings(Object(WP_REST_Request))
#7 /wordpress/core/6.2.2/wp-includes/rest-api/class-wp-rest-server.php(1028): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/v3/payments...', Array, NULL)
#8 /wordpress/core/6.2.2/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch(Object(WP_REST_Request))
#9 /wordpress/core/6.2.2/wp-includes/rest-api.php(410): WP_REST_Server->serve_request('/wc/v3/payments...')
#10 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): rest_api_loaded(Object(WP))
#11 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#12 /wordpress/core/6.2.2/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#13 /wordpress/core/6.2.2/wp-includes/class-wp.php(399): do_action_ref_array('parse_request', Array)
#14 /wordpress/core/6.2.2/wp-includes/class-wp.php(780): WP->parse_request('')
#15 /wordpress/core/6.2.2/wp-includes/functions.php(1334): WP->main('')
#16 /wordpress/core/6.2.2/wp-blog-header.php(16): wp()
#17 /wordpress/core/6.2.2/index.php(17): require('/wordpress/core...')
#18 {main}
  thrown in /wordpress/plugins/woocommerce-payments/6.1.1/includes/wc-payment-api/class-wc-payments-api-client.php on line 2009
```

### To Reproduce

1. Create a fresh Woo Express site: https://woocommerce.com/express/
2. Onboard via WCPay
3. Check for fatals

### Actual behavior

A fatal error is thrown, but TBD if this has any customer- or merchant-facing impact.

### Expected behavior

Ideally, no fatal errors :)

### Additional context
p1689208836019339-slack-C7U3Y3VMY

**Comment by htdat** [comment]
This issue impacts `Fraud`, so assigning to Sigma (based on team responsibilities Pc2DNy-3z-p2) cc @dwainm as team lead. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by tpaksu** [comment]
Unfortunately, we keep the error logs for one month, and I couldn't access the server log that should match the client fatal error given above. I've filtered out the fatals produced on the server since the first of this month, and there are two types of errors that the fraud ruleset system is producing:

```
Exception: An error occurred while toggling zip checks for 1263814: This object cannot be accessed right now because another API request or Stripe process is currently accessing it. If you see this error intermittently, retry the request. If you see this error frequently and are making multiple concurrent requests to a single object, make your requests serially or at a lower rate. in /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/wcpay/class-fraud-ruleset-controller.php:234
Stack trace:
#0 /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/wcpay/class-fraud-ruleset-controller.php(186): WCPay\Fraud_Ruleset_Controller->set_account_avs_status_from_ruleset(Object(WCPay\Authentication\Account), Array)
#1 /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/wcpay/class-api-request-dispatcher.php(167): WCPay\Fraud_Ruleset_Controller->save_fraud_ruleset(Object(WCPay\Core\WCPay_REST_Request))
#2 /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/wcpay/class-api-request-dispatcher.php(105): WCPay\API_Request_Dispatcher->dispatch('WCPay\\Fraud_Rul...', 'save_fraud_rule...', Object(WCPay\Core\WCPay_REST_Request))
#3 /home/wpcom/public_html/wp-includes/rest-api/class-wp-rest-server.php(1188): WCPay\API_Request_Dispatcher->dispatch_callback(Object(WP_REST_Request))
#4 /home/wpcom/public_html/wp-includes/rest-api/class-wp-rest-server.php(1035): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wpcom/v2/sites...', Array, NULL)
#5 /home/wpcom/public_html/wp-includes/rest-api/class-wp-rest-server.php(447): WP_REST_Server->dispatch(Object(WP_REST_Request))
#6 /home/wpcom/public_html/wp-includes/rest-api.php(421): WP_REST_Server->serve_request('/wpcom/v2/sites...')
#7 /home/wpcom/public_html/wp-includes/class-wp-hook.php(310): rest_api_loaded(Object(WP))
#8 /home/wpcom/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#9 /home/wpcom/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#10 /home/wpcom/public_html/wp-includes/class-wp.php(398): do_action_ref_array('parse_request', Array)
#11 /home/wpcom/public_html/wp-includes/class-wp.php(779): WP->parse_request('')
#12 /home/wpcom/public_html/wp-includes/functions.php(1385): WP->main('')
#13 /home/wpcom/public_html/public.api/wp-json/index.php(46): wp()
#14 /home/wpcom/public_html/public.api/wp-json/index.php(49): wpcom_wp_api_run()
#15 {main}
```

and 

```
TypeError: Argument 2 passed to WCPay\Service\Fraud_Outcome_Service::get_fraud_outcome_array_by_id() must be of the type int, string given, called in /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/wcpay/class-fraud-outcome-controller.php on line 130 and defined in /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/wcpay/service/class-fraud-outcome-service.php:82
Stack trace:
#0 /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/wcpay/class-fraud-outcome-controller.php(130): WCPay\Service\Fraud_Outcome_Service->get_fraud_outcome_array_by_id(Object(WCPay\Authentication\Account), 'status')
#1 /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/wcpay/class-api-request-dispatcher.php(167): WCPay\Fraud_Outcome_Controller->get_fraud_outcome_array_by_id(Object(WCPay\Core\WCPay_REST_Request))
#2 /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/wcpay/class-api-request-dispatcher.php(105): WCPay\API_Request_Dispatcher->dispatch('WCPay\\Fraud_Out...', 'get_fraud_outco...', Object(WCPay\Core\WCPay_REST_Request))
#3 /home/wpcom/public_html/wp-includes/rest-api/class-wp-rest-server.php(1188): WCPay\API_Request_Dispatcher->dispatch_callback(Object(WP_REST_Request))
#4 /home/wpcom/public_html/wp-includes/rest-api/class-wp-rest-server.php(1035): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wpcom/v2/sites...', Array, NULL)
#5 /home/wpcom/public_html/wp-includes/rest-api/class-wp-rest-server.php(447): WP_REST_Server->dispatch(Object(WP_REST_Request))
#6 /home/wpcom/public_html/wp-includes/rest-api.php(421): WP_REST_Server->serve_request('/wpcom/v2/sites...')
#7 /home/wpcom/public_html/wp-includes/class-wp-hook.php(310): rest_api_loaded(Object(WP))
#8 /home/wpcom/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#9 /home/wpcom/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#10 /home/wpcom/public_html/wp-includes/class-wp.php(398): do_action_ref_array('parse_request', Array)
#11 /home/wpcom/public_html/wp-includes/class-wp.php(779): WP->parse_request('')
#12 /home/wpcom/public_html/wp-includes/functions.php(1385): WP->main('')
#13 /home/wpcom/public_html/public.api/wp-json/index.php(46): wp()
#14 /home/wpcom/public_html/public.api/wp-json/index.php(49): wpcom_wp_api_run()
#15 {main}
```

I'll try to solve those two instead, and check if the WooExpress onboarding still produces that fatal log.

**Comment by tpaksu** [comment]
@csmcneill, on the other hand, we changed a part of code that's using `is_stripe_connected` to `is_stripe_account_valid`, which will hide the fraud & risk tools before the user is onboarded. Maybe that's why you were seeing this. Can you test with the latest version and see if the fatal is logged again? Maybe this issue was solved by that change.

**Comment by tpaksu** [comment]
I've tested it on https://woo-quickly-instant-salad.wpcomstaging.com/ by onboarding a fake NL account, and on the [logs page](https://woo-quickly-instant-salad.wpcomstaging.com/wp-admin/admin.php?page=wc-status&tab=logs) the fatal is not seen. Waiting confirmation from @csmcneill to close this issue.

**Comment by csmcneill** [comment]
I onboarded with a fresh, live US account (which is what I tested previously) on https://woo-cheerfully-exuberant-wombat.wpcomstaging.com/ and cannot reproduce the issue.

Closing :)
