### ISSUE TITLE
Call to a member function should_use_stripe_platform_on_checkout_page() on null

### ISSUE THREAD

**Issue by kaushikasomaiya** [Automattic/woocommerce-payments#7128]
6705304-zen

Merchant is seeing the below error from WooPayments. Opening this for tracking more such issues.

```

Error Details
=============
An error of type E_ERROR was caused in line 179 of the file public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php. 
Error message: Uncaught Error: Call to a member function should_use_stripe_platform_on_checkout_page() on null in public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-checkout.php:179
Stack trace:
#0 public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-upe-checkout.php(146): WCPay\WC_Payments_Checkout->get_payment_fields_js_config()
#1 public_html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-blocks-payment-method.php(101): WCPay\WC_Payments_UPE_Checkout->get_payment_fields_js_config()
#2 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/PaymentMethodRegistry.php(62): WC_Payments_Blocks_Payment_Method->get_payment_method_data()
#3 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php(93): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_registered_script_data()
#4 public_html/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_data()
#5 public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#6 public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/MiniCart.php(200): do_action()
#8 public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/BlockTypes/AbstractBlock.php(100): Automattic\WooCommerce\Blocks\BlockTypes\MiniCart->enqueue_data()
#9 public_html/wp-includes/class-wp-hook.php(310): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_editor_assets()
#10 public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#11 public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#12 public_html/wp-admin/edit-form-blocks.php(272): do_action()
#13 public_html/wp-admin/post.php(187): require('/home/u70418726...')
#14 {main}
  thrown

```

**Comment by kaushikasomaiya** [comment]
CC: @shendy-a8c 

This might be arising from Cart and Checkout blocks and perhaps in the Gutenberg editor area? 

I don't have steps to replicate yet.

**Comment by timur27** [comment]
Looking into it.

**Comment by shendy-a8c** [comment]
Linked this issue with https://github.com/Automattic/woocommerce-payments/pull/7133 and closing it as the PR has been merged.
