### ISSUE TITLE
Refunding an order via the REST API results in: Uncaught Error: Class 'WCPay\Tracker' not found

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#835]
Refunding an order via the REST API results in the following stack trace:

```
2020-08-24T23:03:40+00:00 CRITICAL Uncaught Error: Class 'WCPay\Tracker' not found in /srv/users/usercb6924e6/apps/usercb6924e6/public/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php:644
Stack trace:
#0 /srv/users/usercb6924e6/apps/usercb6924e6/public/wp-content/plugins/woocommerce/includes/wc-order-functions.php(666): WC_Payment_Gateway_WCPay->process_refund(2890, '1.5', 'Refunded by Rob...')
#1 /srv/users/usercb6924e6/apps/usercb6924e6/public/wp-content/plugins/woocommerce/includes/wc-order-functions.php(595): wc_refund_payment(Object(Automattic\WooCommerce\Admin\Overrides\Order), '1.5', 'Refunded by Rob...')
#2 /srv/users/usercb6924e6/apps/usercb6924e6/public/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version2/class-wc-rest-order-refunds-v2-controller.php(283): wc_create_refund(Array)
#3 /srv/users/usercb6924e6/apps/usercb6924e6/public/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version2/class-wc-rest-order-refunds-v2-controller.php(329):  in /srv/users/usercb6924e6/apps/usercb6924e6/public/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php on line 644
```

**To reproduce**
 - Refund a WC Payments order using endpoint `wc/v2/orders/{ID}/refunds`
 - Recieve the following API response:

```
{"code":"woocommerce_rest_cannot_create_order_refund","message":"An error occurred while attempting to create the refund using the payment gateway API.","data":500}
```

**Environment**
 - WC Payments 1.3.0
 - WC 4.4.1
 - WP 5.5

**Comment by allendav** [comment]
Added to Sprint 18
