### ISSUE TITLE
Most e2e tests failing due to `TimeoutError: Navigation timeout of 25000 ms exceeded`

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#9285]
### Description

Most e2e tests are currently failing due to a `TimeoutError: Navigation timeout of 25000 ms exceeded`.

These failures are visible on the **E2E Tests - All** workflow since the merge of PR #9249. See [this recent **E2E Tests - All** run](https://github.com/Automattic/woocommerce-payments/actions/runs/10462923350/job/28974060414) and search logs for `TimeoutError`.

This can also be reproduced locally when running `npm run test:e2e`.

**Output from the test failure**:

Example snippet from failing tests:

```
  ● Merchant Multi-Currency Settings › Currency Settings › can change the currency rate manually

    TimeoutError: Navigation timeout of 25000 ms exceeded

      at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (node_modules/puppeteer/node_modules/puppeteer-core/src/common/LifecycleWatcher.ts:240:12)

  ● Merchant Multi-Currency Settings › Currency Settings › can change the currency rate manually

    TimeoutError: Waiting for selector `li.enabled-currency.chf` failed: Waiting failed: 10000ms exceeded

      at Timeout.<anonymous> (node_modules/puppeteer/node_modules/puppeteer-core/src/common/WaitTask.ts:91:11)
```

### Additional context

Coincides with merge of PR #9249. Reverting commit a56d57a0cc393e74fa141059adffc1194cf1a13e and building fixes the problem when running `npm run test:e2e` locally.

Commenting out the call to `recordUserEvent` in [woocommerce-payments/client/frontend-tracks/index.js](https://github.com/Automattic/woocommerce-payments/blob/a56d57a0cc393e74fa141059adffc1194cf1a13e/client/frontend-tracks/index.js) on line 8 seems to fix the issue.

https://github.com/Automattic/woocommerce-payments/blob/a56d57a0cc393e74fa141059adffc1194cf1a13e/client/frontend-tracks/index.js#L6-L12

Increasing timeout here to `100000ms` does **not** fix the issue: `TimeoutError: Navigation timeout of 100000 ms exceeded` (`page.setDefaultTimeout( TIMEOUT );`.

https://github.com/Automattic/woocommerce-payments/blob/a56d57a0cc393e74fa141059adffc1194cf1a13e/tests/e2e/config/jest.setup.js#L119

The [**E2E Tests - All** run](https://github.com/Automattic/woocommerce-payments/actions/runs/10452981904) prior to #9249 passes apart from known failing e2e test #9281:

<img width="250" alt="image" src="https://github.com/user-attachments/assets/0b9e5bb0-e183-45e3-8bb3-d22028d522ef">

The [**E2E Tests - All** run](https://github.com/Automattic/woocommerce-payments/actions/runs/10456162342) for #9249 fails across the board:

<img width="300" alt="image" src="https://github.com/user-attachments/assets/c8f25489-8dc1-4b3c-80d1-f58b57b72e2b">

### Priority

**High** due to large amount of e2e failures.

### Reason why this e2e test is broken

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [ ] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

**Comment by Jinksi** [comment]
Running locally with `npm run test:e2e-dev` shows that the tests get stuck at checkout:

<img width="2672" alt="image" src="https://github.com/user-attachments/assets/d7e720f6-e5ad-4578-a7ca-c2f28a7c203d">

~With the following Stripe error in console.~ **Update** this Stripe error shows on successful runs as well.

```
POST https://r.stripe.com/b 400 (Bad Request)
```

**Comment by Jinksi** [comment]
Commenting out the call to `recordUserEvent` in [woocommerce-payments/client/frontend-tracks/index.js](https://github.com/Automattic/woocommerce-payments/blob/a56d57a0cc393e74fa141059adffc1194cf1a13e/client/frontend-tracks/index.js) on line 8 seems to fix the issue.


https://github.com/Automattic/woocommerce-payments/blob/a56d57a0cc393e74fa141059adffc1194cf1a13e/client/frontend-tracks/index.js#L6-L12
